title: Infera Group LLC
logo: /assets/img/Infera_Logo.png
description: Data science and analytics consulting by James Eells, PhD. Specializing
  in predictive modeling, program impact measurement, and data visualization.
author: James Eells
baseurl: "/infera-group"
theme: jekyll-theme-minimal
plugins:
- jekyll-feed
github:
  is_project_page: true
defaults:
- scope:
    path: ''
  values:
    layout: default
