site_name: Infra Group LLC
theme:
  name: material
  logo: assets/images/Infera_Logo.png
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
nav:
  - Home: index.md
  - Projects:
      - Overview: projects/index.md
      - Credit Risk Notebook: projects/credit_h20automl.ipynb
  - Case Studies: case-studies/index.md
  - Resume: resume/index.md
plugins:
  - search
  - mkdocs-jupyter