name: Phase 0 - Python Azure Starter

on:
  push:
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Lint (Black)
        run: |
          python -m pip install black
          black --check .

      - name: Run simple tests (shared utilities)
        run: |
          python -m pytest -q || echo "No tests found; proceeding"

      - name: MLflow end-to-end dry run
        env:
          MLFLOW_TRACKING_URI: ./mlruns
          MLFLOW_EXPERIMENT_NAME: Phase0_Demo
        run: |
          python mlflow_run_template.py

      - name: Echo completion
        run: echo "Phase 0 workflow complete"
